default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: liviaiwanicki
      password: beeper999
      port: 5432
      dbname: liviaiwanicki
      schema: public  # You can modify the schema if needed
      threads: 4
      keepalives_idle: 0
